const fs = require('fs');

const destinations = [
  'Thailand','Cambodia','Laos','Vietnam','Japan','Baja','San Diego','California','Hawaii','Alaska',
  'Utah','Colorado','Arizona','Nevada','Midwest','Texas','Florida','New England','New York','Colombia',
  'Brazil','DR','Puerto Rico','Amsterdam','Greece','Italy','Eastern Europe','Germany'
];

const D = {
  TH:'Thailand', KH:'Cambodia', LA:'Laos', VN:'Vietnam', JP:'Japan', BJ:'Baja', SD:'San Diego',
  CA:'California', HI:'Hawaii', AK:'Alaska', UT:'Utah', CO:'Colorado', AZ:'Arizona', NV:'Nevada',
  MW:'Midwest', TX:'Texas', FL:'Florida', NE:'New England', NY:'New York', COL:'Colombia',
  BR:'Brazil', DR:'DR', PR:'Puerto Rico', AMS:'Amsterdam', GR:'Greece', IT:'Italy', EE:'Eastern Europe', DE:'Germany',
  ALL: 'ALL'
};

// [num, category, itemName, recommendedProduct, ASIN, destinations[]]
const items = [
  [1,'Surfing','Surf changing poncho / robe','SUN CUBE Surf Poncho with Hood','B0C6YKR4YW',[D.BJ,D.SD,D.CA,D.HI,D.PR,D.BR]],
  [2,'Surfing','Surf ear plugs','Creatures of Leisure SurfEars 3.0','B086D6NDY8',[D.CA,D.HI,D.PR]],
  [3,'Surfing','Wetsuit 3/2mm (cold water)','O\'Neill Reactor-2 3/2mm Back Zip','B07885K73W',[D.CA,D.AK,D.NE,D.UT]],
  [4,'Surfing','Zinc oxide face sunscreen stick','Sun Bum Mineral SPF 50 Face Stick','B0721M83FL',[D.BJ,D.SD,D.CA,D.HI,D.CO,D.UT]],
  [5,'Surfing','Surf wax','Mr. Zogs Sex Wax Tropical','B07BVCC6H3',[D.BJ,D.SD,D.CA,D.HI,D.PR]],
  [6,'Diving','Dive computer watch','Suunto D5 Wrist Dive Computer','B07NGVLR1P',[D.TH,D.HI,D.FL,D.GR,D.DR]],
  [7,'Diving','Dive torch / underwater light','WINDFIRE Dive Light 60m IPX8','B07WCN73BV',[D.HI,D.FL]],
  [8,'Diving','Mesh dive gear bag','AKONA Adventure Mesh Backpack','B003JPA1WA',[D.TH,D.HI,D.FL,D.GR,D.DR]],
  [9,'Diving','GoPro dome port (half-water shots)','TELESIN Dome Port for GoPro 9-13','B08JJ9TPJX',[D.LA,D.HI,D.FL,D.BR,D.DR]],
  [10,'Diving','Mask defog spray','Stream2Sea Biodegradable Defog 3-Pack','B088YB681B',[D.TH,D.HI,D.FL,D.GR,D.DR,D.PR]],
  [11,'Kayaking','Paddle gloves (neoprene)','NRS Catalyst 2mm Neoprene Glove','B01AYH1O7Q',[D.AK,D.MW]],
  [12,'Kayaking','Dry bag phone lanyard','UNBREAKcable Floating Waterproof Pouch 2-Pack','B0BZH852G3',[D.HI,D.AK,D.FL,D.PR]],
  [13,'Kayaking','Inflatable travel SUP','iROCKER All-Around 11\' Inflatable SUP','B08N5NLV7K',[D.SD,D.HI,D.FL]],
  [14,'Fishing','Travel fishing rod (telescopic)','KastKing BlackHawk II Telescopic 7\'','B07N454L81',[D.BJ,D.AK,D.CO,D.TX,D.FL,D.MW]],
  [15,'Fishing','Tackle travel organizer','Plano 3500 ProLatch Stowaway 4-Pack','B00CKIG4AA',[D.BJ,D.AK]],
  [16,'Fishing','Fishing sun gloves (UPF 50+)','KastKing Sol Armis UPF 50+ Fingerless','B07FYK146P',[D.BJ,D.AK]],
  [17,'Skiing','Ski socks','Darn Tough Edge OTC Midweight Ski Sock','B0CJ4924ZW',[D.JP,D.CA,D.UT,D.CO,D.NE,D.IT,D.DE]],
  [18,'Skiing','Ski goggles','Smith Squad ChromaPop (2 lenses)','B00L8CWSM2',[D.JP,D.CA,D.UT,D.CO,D.NE,D.IT,D.DE]],
  [19,'Skiing','Balaclava / ski mask','Tough Headwear Fleece Balaclava','B019F18TX4',[D.JP,D.CO,D.NE]],
  [20,'Skiing','Ski gloves (waterproof insulated)','Black Diamond Guide GORE-TEX Gloves','B00TUTK4A8',[D.CO,D.NE]],
  [21,'Skiing','Helmet liner (thin beanie)','Smartwool Merino 150 Beanie','B0721R18BX',[D.JP,D.CA,D.UT,D.CO,D.NE,D.IT,D.DE]],
  [22,'Skiing','Ski / snowboard lock','Bosvision Retractable Cable Lock','B00DG2TNB6',[D.UT,D.CO]],
  [23,'Skiing','Wrist guards (snowboarding)','Demon Flexmeter D3O Wrist Guards','B017HZ9OXY',[D.CO]],
  [24,'Skiing','Boot dryer (portable)','DryGuy Travel Dry DX','B0FD8KVHF2',[D.CO]],
  [25,'Winter','Snowshoes','MSR Lightning Ascent with Paragon Bindings','B07W4SBGGG',[D.AK]],
  [26,'Winter','Microspikes / ice cleats','Kahtoola MICROspikes','B0030I3Y48',[D.AK,D.CO,D.NE]],
  [27,'Winter','Gaiters (snow/mud)','Outdoor Research Crocodile GORE-TEX','B0D6SS871C',[D.AK]],
  [28,'Cycling','Padded cycling shorts','Baleaf 3D Padded Bike Shorts UPF 50+','B0D93W6W6V',[D.KH,D.AMS,D.NE,D.IT,D.DE]],
  [29,'Cycling','Bike phone mount','Quad Lock Out Front Bike Mount','B0881N14PH',[D.AMS,D.DE]],
  [30,'Cycling','Compact bike lock (folding)','ABUS Bordo Granit X-Plus 6500','B09ZNHMN36',[D.AMS,D.DE]],
  [31,'Cycling','Rear bike light (USB rechargeable)','BLITZU Cyborg 120T 2-Pack','B00W7Y27CQ',[D.AMS]],
  [32,'Cycling','Cycling sunglasses','Tifosi Sledge (3 lenses included)','B087YVZ3TV',[D.AMS,D.IT,D.DE,D.NE]],
  [33,'Mountain Biking','MTB gloves (full finger)','Fox Racing Ranger Glove','B0B8N8Z2RV',[D.CA,D.UT,D.AZ,D.CO]],
  [34,'Mountain Biking','MTB knee pads','G-Form Pro-X3 SmartFlex Knee Guards','B0BZ958FTJ',[D.CA,D.UT,D.AZ,D.CO]],
  [35,'Mountain Biking','Hydration pack (Camelbak)','CamelBak M.U.L.E. 12 (100oz)','B09PZ98JXB',[D.UT,D.CO]],
  [36,'Camping','Travel hammock (with straps)','ENO DoubleNest Hammock','B001DDTE5A',[D.LA,D.BJ,D.TX,D.MW,D.COL]],
  [37,'Camping','Solar / rechargeable lantern','LuminAID PackLite Max 2-in-1','B0CVYMMHJ4',[D.BJ,D.AK]],
  [38,'Camping','Compact camp stove','Jetboil Flash 1.0L Cooking System','B0DZ9GB3Y5',[D.AK,D.MW]],
  [39,'Camping','Sleeping bag liner (silk)','Sea to Summit Premium Silk Liner Mummy','B0B8QSZY6N',[D.COL,D.EE]],
  [40,'Camping','Multi-tool','Leatherman Wave+ 18-in-1','B079MJBP21',[D.BJ,D.CA,D.AK,D.UT,D.CO]],
  [41,'Camping','Fire starter cubes (waterproof)','Waterproof Fire Starter Squares 100pc','B07RKD9CF8',[D.BJ,D.AK,D.UT,D.CO]],
  [42,'Camping','Folding camp chair','Helinox Chair Zero (1.1 lbs)','B01M07GTOE',[D.BJ,D.CA,D.AK,D.UT,D.CO,D.AZ,D.NV,D.TX,D.MW]],
  [43,'Camping','Packable camp pillow','Therm-a-Rest Compressible Pillow','B0CDGQC1L6',[D.AK,D.UT,D.CO]],
  [44,'Rock Climbing','Climbing shoes (travel pair)','La Sportiva Tarantulace','B07BCK9CWR',[D.TH,D.CA,D.UT]],
  [45,'Rock Climbing','Chalk bag + chalk ball','Sukoa Chalk Bag Quick-Clip Belt','B07RTVZ3BC',[D.CA,D.UT]],
  [46,'Canyoneering','Canyoneering / belay gloves','Petzl CORDEX Lightweight Belay Gloves','B00ACM4DRC',[D.UT,D.DR,D.IT]],
  [47,'Canyoneering','Climbing helmet (lightweight)','Petzl BOREO Helmet','B0BSBDZK44',[D.UT,D.IT]],
  [48,'Road Trips','Car phone mount','iOttie Easy One Touch 6','B0C1HP8N5D',[D.BJ,D.CA,D.UT,D.AZ,D.NV,D.TX,D.MW,D.NE]],
  [49,'Road Trips','Car charger (dual USB-C 40W)','Anker PowerDrive III Duo 40W','B0843SCLYH',[D.BJ,D.CA,D.UT,D.AZ,D.NV,D.TX,D.MW,D.NE]],
  [50,'Road Trips','Collapsible cooler bag','CleverMade Collapsible Cooler 30-Can','B0B3Y825HJ',[D.BJ,D.SD,D.CA,D.TX,D.FL,D.MW]],
  [51,'Road Trips','Lumbar support cushion','KULIK SYSTEM Lumbar Support','B08295Y3R7',[D.BJ,D.CA,D.AZ,D.TX,D.NE]],
  [52,'Road Trips','Dash cam','VIOFO A229 Plus Dual 2K HDR','B0CKX14L34',[D.VN,D.BJ,D.CA,D.AZ]],
  [53,'Road Trips','Windshield sun shade','EcoNour Car Sun Shade 64x32','B01KIFISX2',[D.BJ,D.AZ,D.NV,D.AK,D.UT,D.TX,D.FL]],
  [54,'Road Trips','Roadside emergency kit','LIANXIN Roadside Emergency Kit','B0CQBX3JZ6',[D.UT,D.AZ,D.NV,D.BJ,D.TX]],
  [55,'Wildlife','Compact binoculars (10x42)','Nikon PROSTAFF P3 10x42','B0B3JSRZFJ',[D.BJ,D.CA,D.HI,D.AK,D.CO,D.TX,D.FL,D.NE,D.MW,D.COL,D.DR]],
  [56,'Wildlife','Bear spray (with holster)','Counter Assault 10.2oz with Holster','B0CXG2JR68',[D.CA,D.AK,D.CO]],
  [57,'Wildlife','Bug head net (mosquito mesh)','EVEN NATURALS Premium Head Net 620/sq in','B01EKFQFDG',[D.AK,D.MW,D.FL,D.COL,D.BR]],
  [58,'Wildlife','Bird field guide','Sibley Guide to Birds 2nd Edition','030795790X',[D.COL,D.TX,D.AK,D.FL]],
  [59,'Photography','GoPro Hero (action camera)','GoPro HERO13 Black 5.3K60','B0DCM34GXX',[D.TH,D.LA,D.VN,D.BJ,D.SD,D.HI,D.AK,D.CO,D.TX,D.FL,D.COL,D.BR,D.DR,D.PR,D.GR]],
  [60,'Photography','Compact travel tripod','Peak Design Travel Tripod Aluminum','B085BQS6K4',[D.JP,D.CA,D.UT,D.AZ,D.NV,D.NE,D.NY,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [61,'Photography','Drone (DJI Mini under 250g)','DJI Mini 4 Pro (RC 2)','B0CFF1SJ3P',[D.CA,D.HI,D.UT,D.AZ,D.NV,D.GR,D.IT]],
  [62,'Photography','Phone lens kit (wide angle)','Moment 18mm Wide Lens T-Series','B0CNY8VK2N',[D.NY,D.VN,D.IT]],
  [63,'Photography','Camera rain cover','Altura Photo Professional Rain Cover','B004AH10K8',[D.AK,D.NE,D.COL,D.VN]],
  [64,'Photography','ND filter set','K&F Concept Nano-X ND4/ND8/ND64/ND1000','B08V1DPQ69',[D.UT,D.AZ]],
  [65,'Photography','Memory card case','Pelican 0915 Water/Shock Resistant','B005D2JE2A',[D.JP,D.AK,D.UT,D.AZ,D.IT,D.GR]],
  [66,'Stargazing','Red LED headlamp (night vision)','Black Diamond Cosmo 350-R Rechargeable','B09TND94HB',[D.CA,D.HI,D.AK,D.UT,D.CO,D.AZ,D.NV]],
  [67,'Stargazing','Stargazing phone mount','SVBONY Universal Phone Adapter 25-48mm','B01K7M0JEM',[D.HI,D.UT,D.AZ]],
  [68,'Beach','Sand-free beach towel','Elite Trend Microfiber 78x35 Quick Dry','B0892WHFK5',[D.TH,D.KH,D.BJ,D.SD,D.HI,D.TX,D.FL,D.DR,D.PR,D.GR,D.BR]],
  [69,'Beach','Pop-up beach sun shade','OutdoorMaster UPF 50+ Beach Tent 3-4 Person','B06XNVVKYG',[D.SD,D.HI,D.FL,D.DR]],
  [70,'Beach','Waterproof Bluetooth speaker','JBL Clip 4 IP67 10hr Battery','B08PJ7JMQM',[D.BJ,D.SD,D.NV,D.TX,D.FL,D.DR,D.PR,D.GR,D.BR]],
  [71,'Beach','Beach bag (mesh / sand drains)','XL Mesh Beach Bag Tote','B07DLWS8XR',[D.BJ,D.SD,D.HI,D.FL,D.DR,D.PR,D.GR]],
  [72,'Beach','Floating waterproof phone case','CaliCase Universal Floating Pouch IPX8','B011EDUHJA',[D.LA,D.TX,D.FL,D.DR,D.BR]],
  [73,'Cultural','Lightweight scarf / sarong','World of Shawls Sarong 110x200cm','B01LVW1AX5',[D.TH,D.KH,D.LA,D.VN]],
  [74,'Cultural','Travel slippers / indoor shoes','Scurtain Foldable Travel Slippers','B0CF3ZDP5X',[D.JP]],
  [75,'Cultural','Travel chopsticks / utensil set','finessCity Titanium Cutlery Set (2.6oz)','B0788VW2WS',[D.TH,D.LA,D.VN,D.JP]],
  [76,'Cultural','Coin purse','imeetu Leather Coin Purse 2-Zip','B088KQFY3Y',[D.JP]],
  [77,'Urban','Comfortable walking shoes','New Balance 840v5 Walking Shoe','B08PDFZSDP',[D.KH,D.JP,D.SD,D.NV,D.MW,D.FL,D.NE,D.NY,D.COL,D.BR,D.PR,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [78,'Urban','Anti-theft crossbody bag','Pacsafe Metrosafe LS200 (7L slash-proof)','B017BPMS3I',[D.TH,D.VN,D.NY,D.COL,D.BR,D.AMS,D.GR,D.IT,D.EE]],
  [79,'Urban','RFID-blocking wallet','VULKIT Passport Wallet Nappa Leather RFID','B0B8219DRL',[D.NY,D.COL,D.BR,D.AMS,D.GR,D.IT,D.EE]],
  [80,'Urban','Portable power bank (20000mAh)','Anker Nano Power Bank 20K 30W USB-C','B0DWCPS2Y4',[D.ALL]],
  [81,'Urban','Compact travel umbrella','Repel Windproof 85MPH Auto Open/Close','B0CF63651G',[D.VN,D.JP,D.MW,D.NE,D.NY,D.COL,D.AMS,D.IT,D.EE,D.DE]],
  [82,'Urban','Noise-canceling headphones','Sony WH-1000XM5','B09XS7JWHH',[D.JP,D.MW,D.NY,D.AMS,D.EE,D.DE]],
  [83,'Cold Weather','Merino wool base layer top','Smartwool Classic Thermal 250 Crew','B0B1937J29',[D.JP,D.AK,D.CO,D.NE,D.EE,D.DE]],
  [84,'Cold Weather','Merino wool base layer bottoms','Smartwool Classic Thermal 250 Bottom','B09PTPJSQL',[D.AK,D.CO,D.NE]],
  [85,'Cold Weather','Packable down jacket','Amazon Essentials Packable Puffer','B0738JFRD1',[D.VN,D.JP,D.CA,D.AK,D.CO,D.NE,D.NY,D.MW,D.COL,D.IT,D.EE,D.DE]],
  [86,'Cold Weather','Fleece quarter-zip mid-layer','Patagonia Better Sweater 1/4-Zip','B083VHBBDL',[D.AK,D.CO,D.NE,D.EE,D.DE]],
  [87,'Cold Weather','Waterproof hardshell jacket','Outdoor Research Helium Rain Jacket','B0DD8K3K5R',[D.AK,D.CO,D.NE,D.AMS,D.EE]],
  [88,'Cold Weather','Touchscreen thermal gloves','TRENDOUX Winter Touchscreen Gloves','B0825RFGR9',[D.JP,D.AK,D.CO,D.NE,D.NY,D.EE,D.DE]],
  [89,'Cold Weather','Wool beanie','Carhartt Knit Cuffed Beanie','B0CMM21PRL',[D.JP,D.AK,D.CO,D.NE,D.NY,D.EE,D.DE]],
  [90,'Cold Weather','Neck gaiter / buff','BUFF Original EcoStretch UPF 50','B0CBQM96SX',[D.VN,D.KH,D.AK,D.CO]],
  [91,'Cold Weather','Hand/toe warmers','HotHands Combo Pack (24H + 8T)','B06ZYW6HDK',[D.JP,D.AK,D.CO,D.NE,D.EE,D.DE]],
  [92,'Hiking','Waterproof hiking boots','Merrell Moab 3 Mid Waterproof','B0C64B38Z8',[D.VN,D.JP,D.CA,D.HI,D.AK,D.UT,D.CO,D.AZ,D.NE,D.COL,D.DR,D.PR,D.GR,D.IT,D.EE,D.DE]],
  [93,'Hiking','Collapsible trekking poles','Black Diamond Distance Carbon Z','B077SQ17JV',[D.JP,D.CA,D.AK,D.UT,D.CO,D.AZ,D.NE,D.COL,D.IT,D.EE,D.DE]],
  [94,'Hiking','Hiking daypack (20-30L)','Osprey Daylite Plus 20L','B01I2P52WU',[D.VN,D.CA,D.HI,D.AK,D.UT,D.CO,D.AZ,D.TX,D.NE,D.COL,D.DR,D.GR,D.IT,D.EE,D.DE]],
  [95,'Hiking','Hydration bladder (3L)','CamelBak Crux 3L Reservoir','B01LA5FCJ2',[D.CA,D.AK,D.UT,D.CO,D.AZ,D.NV,D.TX]],
  [96,'Hiking','Wool hiking socks','Darn Tough Hiker Boot Full Cushion','B000XIEAH8',[D.VN,D.JP,D.AK,D.UT,D.CO,D.NE,D.COL,D.GR,D.IT,D.EE,D.DE]],
  [97,'Hiking','Headlamp','Black Diamond Spot 400','B09NQK2581',[D.KH,D.LA,D.VN,D.JP,D.HI,D.AK,D.UT,D.CO,D.AZ,D.COL,D.PR]],
  [98,'Hiking','Moleskin / blister prevention','Dr. Scholl\'s Moleskin Plus 2-Pack','B082LPPKS8',[D.CO,D.AZ]],
  [99,'Hiking','Portable water filter','Sawyer Squeeze SP131 (0.1 micron)','B0988M1RTF',[D.KH,D.LA,D.AK,D.MW,D.COL]],
  [100,'Hiking','Trail gaiters (ankle)','Outdoor Research Rocky Mountain Low','B009Q1AAHM',[D.UT,D.AZ]],
  [101,'Desert','Wide-brim sun hat','Columbia Bora Bora II Booney UPF 50','B07NPPJH21',[D.KH,D.BJ,D.CA,D.UT,D.AZ,D.NV,D.TX,D.GR]],
  [102,'Desert','UPF 50+ long-sleeve sun shirt','Columbia PFG Terminal Tackle LS','B08FGX3G41',[D.KH,D.BJ,D.SD,D.HI,D.UT,D.AZ,D.NV,D.TX,D.GR,D.BR]],
  [103,'Desert','Insulated water bottle (32oz)','Hydro Flask 32oz Wide Mouth','B09R8KRRDX',[D.KH,D.BJ,D.CA,D.HI,D.UT,D.AZ,D.NV,D.TX,D.GR,D.DR]],
  [104,'Desert','Cooling towel','Mission Original Cooling Towel UPF 50','B0087DQQF0',[D.TH,D.KH,D.AZ,D.NV,D.TX,D.FL,D.DR]],
  [105,'Desert','Snake gaiters (ankle protection)','TurtleSkin SnakeArmor Gaiters','B00ITZDL90',[D.UT,D.AZ,D.TX]],
  [106,'Security','Money belt (hidden)','Alpha Keeper RFID Money Belt','B01C2R3TZG',[D.COL,D.BR,D.IT,D.EE]],
  [107,'Security','Portable door lock','Addalock Original Portable Door Lock','B00186URTY',[D.BR,D.EE]],
  [108,'Security','Door stop alarm','SABRE 120dB Door Stop Alarm','B00M30SQGA',[D.COL,D.BR,D.EE]],
  [109,'Security','AirTag / luggage tracker','Apple AirTag 4-Pack','B0D54JZTHY',[D.TH,D.VN,D.JP,D.COL,D.BR,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [110,'Security','TSA-approved luggage lock','Forge TSA Lock 4-Pack','B01N7ILPEL',[D.ALL]],
  [111,'Health','Motion sickness bands','Sea-Band Anti-Nausea Wristband','B001F731N0',[D.TH,D.VN,D.BJ,D.HI,D.AK,D.FL,D.NE,D.COL,D.DR,D.GR,D.IT]],
  [112,'Health','Melatonin (jet lag)','OLLY Sleep Melatonin 3mg Gummies 60ct','B07NZKSFKM',[D.TH,D.JP,D.BR,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [113,'Health','Probiotics (travel gut health)','Florastor Daily Probiotic 100 Capsules','B01NB0G1V8',[D.TH,D.KH,D.VN,D.COL,D.BR]],
  [114,'Health','Picaridin insect repellent','Sawyer 20% Picaridin Pump Spray 4oz','B0DK41BC2C',[D.TH,D.KH,D.LA,D.VN,D.COL,D.BR]],
  [115,'Health','Altitude supplement','Zaca Altitude Support Chewable Tablets','B0CFK86KFY',[D.CO,D.COL]],
  [116,'Health','Activated charcoal tablets','NaturaLife Labs Activated Charcoal 100ct','B078T354SC',[D.TH,D.KH,D.VN,D.COL,D.BR]],
  [117,'Health','Mineral sunscreen face stick (zinc)','Sun Bum Mineral SPF 50 Face Stick','B0721M83FL',[D.BJ,D.CA,D.HI,D.UT,D.CO]],
  [118,'Comfort','Compression socks (long-haul)','Sockwell In Flight Merino 15-20mmHg','B089DRF9WM',[D.TH,D.JP,D.AK,D.NY,D.BR,D.IT]],
  [119,'Comfort','Sleep mask (contoured blackout)','Manta Sleep Mask Adjustable Eye Cups','B07PRG2CQY',[D.JP,D.NY,D.EE]],
  [120,'Comfort','Ear plugs (sleeping)','Loop Quiet 2 Reusable 24dB','B0D3V6Y38G',[D.NY,D.EE]],
  [121,'Comfort','Inflatable foot rest (airplane)','Flypal Adjustable Inflatable Foot Rest','B074T9CP81',[D.TH,D.JP,D.BR,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [122,'Comfort','Packable duffel / weekender bag','Gonex 40L Packable Travel Duffle','B0CKXH6M2L',[D.JP,D.NY]],
  [123,'Electronics','Universal travel adapter (USB-C)','EPICKA TA-105 USB-C + 4 USB-A','B078S3M2NX',[D.TH,D.KH,D.LA,D.VN,D.JP,D.COL,D.BR,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [124,'Electronics','GaN multi-port USB-C charger','Anker 735 Nano II 65W 3-Port GaN','B09C5RG6KV',[D.TH,D.KH,D.LA,D.VN,D.JP,D.COL,D.BR,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [125,'Electronics','Cable organizer pouch','BAGSMART Large Electronics Organizer','B017SKRWL4',[D.TH,D.KH,D.LA,D.VN,D.JP,D.COL,D.BR,D.AMS,D.GR,D.IT,D.EE,D.DE]],
  [126,'Electronics','Kindle / e-reader','Kindle Paperwhite 16GB 7" 12th Gen','B0CFPJYX7P',[D.JP,D.MW,D.NE,D.NY,D.AMS,D.GR,D.IT,D.EE,D.DE,D.DR]],
  [127,'Electronics','Transit card holder / lanyard','WALNEW RFID Neck Pouch Passport Holder','B07WPRHB9K',[D.JP,D.AMS,D.IT,D.EE,D.DE]],
  [128,'Rain','Rain pants (lightweight packable)','Outdoor Research Helium Rain Pants (5.4oz)','B0DDJX8JD9',[D.HI,D.AK,D.UT,D.COL,D.PR,D.BR]],
  [129,'Rain','Waterproof backpack cover','Osprey Ultralight Raincover','B0D5MT8XBY',[D.VN,D.AK,D.COL,D.BR,D.PR]],
  [130,'Rain','Quick-dry travel pants (convertible)','Columbia Silver Ridge Convertible UPF 50','B006ZS848Q',[D.LA,D.COL]],
  [131,'Laundry','Travel laundry detergent sheets','Travelon Laundry Soap Sheets 50ct','B000Y0CL8K',[D.TH,D.LA]],
  [132,'Laundry','Portable clothesline (with clips)','HAWATOUR Retractable Clothesline 12 Pins','B074QKYGTT',[D.TH,D.KH,D.LA,D.VN,D.JP]],
  [133,'Yoga','Travel yoga mat (foldable 2mm)','Gaiam Folding Travel Yoga Mat 68x24','B019DKV5MY',[D.TH]],
  [134,'Fitness','Resistance bands (travel set)','Fit Simplify Resistance Bands Set of 5','B01AVDVHTI',[D.TH,D.HI]],
  [135,'Family','Kid carrier backpack (hiking)','Osprey Poco Child Carrier with Sunshade','B0DZ9J8THX',[D.HI,D.AK,D.UT,D.CO,D.AZ,D.FL]],
  [136,'Family','Kids volume-limited headphones','Puro Sound Labs BT2200 Plus 85dB','B0C3T39C58',[D.FL]],
  [137,'Family','Portable travel high chair','Inglesina Fast Table Chair','B00IOGIM9S',[D.FL]],
  [138,'Family','Baby-safe mineral sunscreen','Thinkbaby SPF 50+ Zinc Oxide 3oz','B004CDQ73K',[D.SD,D.HI,D.FL,D.DR]],
  [139,'Hot Springs','Quick-dry small towel (onsen-size)','PackTowl Personal Hand Size 16.5x36','B079ZRN1M6',[D.JP,D.CO,D.EE,D.DE]],
  [140,'Hot Springs','Waterproof valuables pouch','GLBSUNION Triple Zip Lock Dry Bag 2-Pack','B07QRTYWQ8',[D.JP,D.CO,D.EE,D.DE]],
  [141,'Food','Collapsible silicone food containers','CARTINTS Silicone Collapsible 32oz','B07Z4RGJLK',[D.TH,D.VN,D.JP]],
  [142,'Food','Insulated wine tumbler (stemless)','YETI Rambler 10oz Wine Tumbler MagSlider','B08RLLJ8MH',[D.BJ,D.CA,D.PR,D.GR,D.IT,D.DE]],
  [143,'Sun','Polarized sunglasses (glacier/water)','Knockaround Premiums Polarized UV400','B0BHL23CDX',[D.BJ,D.CA,D.HI,D.AK,D.UT,D.CO,D.AZ,D.NV,D.GR]],
  [144,'Sun','SPF lip balm (high altitude)','Sun Bum SPF 30 Lip Balm 3-Pack','B072KGPLX6',[D.AK,D.UT,D.CO,D.AZ]],
];

// Build CSV
const header = ['#','Category','Item Name','Recommended Product','ASIN','Amazon Link', ...destinations];

const rows = items.map(([num, cat, name, product, asin, dests]) => {
  const amazonUrl = `https://www.amazon.com/dp/${asin}?tag=discoverphili-20`;
  const cells = [num, cat, `"${name}"`, `"${product}"`, asin, amazonUrl];
  destinations.forEach(d => {
    if (dests.includes('ALL') || dests.includes(d)) {
      cells.push('x');
    } else {
      cells.push('');
    }
  });
  return cells.join(',');
});

const csv = [header.join(','), ...rows].join('\n');
fs.writeFileSync('C:\\Users\\scott\\documents\\discover-philippines\\amazon-affiliate-items.csv', csv);
console.log(`Generated ${rows.length} rows x ${header.length} columns`);
